import type { Tutorial } from "@/types/Tutorial";

export async function fetchTutorials(limit = 6): Promise<Tutorial[]> {
    // Simula un retraso de red
    await new Promise((resolve) => setTimeout(resolve, 800));

    const tutorials: Tutorial[] = [
        {
            id: "1",
            title: "Introducción a SwiftUI: Construyendo Interfaces Declarativas con Swift",
            description:
                "Descubre los fundamentos de SwiftUI y cómo crear interfaces de usuario modernas y reactivas para aplicaciones iOS.",
            content:
                '# Introducción a SwiftUI\n\nSwiftUI es un framework moderno de Apple que permite crear interfaces de usuario para todas las plataformas de Apple (iOS, macOS, watchOS, tvOS) utilizando un enfoque declarativo y unificado.\n\n## Requisitos Previos\n\n- Conocimientos básicos de Swift\n- Xcode 14 o superior\n- macOS Ventura o posterior\n\n## ¿Qué es SwiftUI?\n\nSwiftUI es un framework moderno de Apple que permite crear interfaces de usuario para todas las plataformas de Apple (iOS, macOS, watchOS, tvOS) utilizando un enfoque declarativo y unificado.\n\n### Características Principales\n\n- 🎨 Diseño declarativo\n- 🔄 Actualización automática de la interfaz\n- 💻 Multiplataforma\n- 🚀 Previsualización en tiempo real\n\n## Tu Primer Componente en SwiftUI\n\nVamos a crear un componente simple que muestre una tarjeta de perfil:\n\n```swift\nimport SwiftUI\n\nstruct ProfileCard: View {\n    var body: some View {\n        VStack(alignment: .leading, spacing: 10) {\n            Image(systemName: "person.circle.fill")\n                .resizable()\n                .aspectRatio(contentMode: .fit)\n                .frame(width: 100, height: 100)\n                .foregroundColor(.blue)\n            \n            Text("Carlos Rodríguez")\n                .font(.title)\n                .fontWeight(.bold)\n            \n            Text("Desarrollador iOS")\n                .font(.subheadline)\n                .foregroundColor(.secondary)\n        }\n        .padding()\n        .background(Color.white)\n        .cornerRadius(10)\n        .shadow(radius: 5)\n    }\n}\n```\n\n## Componentes Fundamentales de SwiftUI\n\n### 1. VStack y HStack\n\nSwiftUI utiliza stacks para organizar vistas:\n\n```swift\nHStack {\n    Text("Izquierda")\n    Text("Derecha")\n}\n\nVStack {\n    Text("Arriba")\n    Text("Abajo")\n}\n```\n\n## Estados y Binding\n\nSwiftUI introduce el concepto de estado con `@State` y `@Binding`:\n\n```swift\nstruct CounterView: View {\n    @State private var count = 0\n    \n    var body: some View {\n        VStack {\n            Text("Contador: \\(count)")\n            Button("Incrementar") {\n                count += 1\n            }\n        }\n    }\n}\n```\n\n## Consejos Pro\n\n1. Usa `Preview` para desarrollo rápido\n2. Mantén tus vistas pequeñas y enfocadas\n3. Aprovecha los modificadores para estilizar\n4. Utiliza `@State` para manejar estados locales\n\n## Conclusión\n\nSwiftUI no es solo una librería, es una nueva forma de pensar en el desarrollo de interfaces. Su enfoque declarativo y su estrecha integración con el ecosistema de Apple lo convierten en una herramienta poderosa para desarrolladores iOS.\n\n¡Felicidades! Has dado tus primeros pasos en SwiftUI. 🎉🚀',
            category: "SwiftUI",
            level: "Principiante",
            date: "2024-04-13",
            imageUrl: "/images/tutorials/swiftui-intro.jpg",
            author: {
                name: "Alvaro Guerra",
                avatar: "/images/authors/alvaro.jpg",
                bio: "Desarrollador iOS con 5 años de experiencia especializado en SwiftUI y arquitecturas modernas de desarrollo móvil.",
            },
            tags: ["SwiftUI", "iOS Development", "UI Framework", "Apple Ecosystem"],
            isPublished: true,
            slug: "introduccion-swiftui",
            readTime: 10,
            createdAt: "2024-04-01T00:00:00Z",
            updatedAt: "2024-04-10T00:00:00Z",
        },
        {
            id: "2",
            title: "Swift Concurrency: async/await",
            description: "Domina el nuevo modelo de concurrencia de Swift con async/await y actores.",
            content: "# Swift Concurrency\n\nEn Swift 5.5, Apple introdujo...",
            category: "Swift",
            level: "Intermedio",
            date: "2023-10-02",
            imageUrl: "/images/tutorials/swiftui-intro.jpg",
            author: {
                name: "Alvaro Guerra",
                avatar: "/images/authors/alvaro.jpg",
                bio: "Desarrollador iOS con 5 años de experiencia especializado en SwiftUI y arquitecturas modernas de desarrollo móvil.",
            },
            tags: ["Swift 5.5", "Concurrency", "async/await"],
            isPublished: true,
            slug: "swift-concurrency",
            readTime: 12,
            createdAt: "2024-04-01T00:00:00Z",
            updatedAt: "2024-04-10T00:00:00Z",
        },
        {
            id: "3",
            title: "Core Data con SwiftUI",
            description: "Aprende a integrar Core Data en tus aplicaciones SwiftUI para persistencia de datos.",
            content: "# Core Data con SwiftUI\n\nCore Data es el framework de persistencia...",
            category: "Frameworks",
            level: "Intermedio",
            date: "2023-10-18",
            imageUrl: "/images/tutorials/swiftui-intro.jpg",
            author: {
                name: "Alvaro Guerra",
                avatar: "/images/authors/alvaro.jpg",
                bio: "Desarrollador iOS con 5 años de experiencia especializado en SwiftUI y arquitecturas modernas de desarrollo móvil.",
            },
            tags: ["Core Data", "SwiftUI", "Persistencia"],
            isPublished: true,
            slug: "core-data-swiftui",
            readTime: 15,
            createdAt: "2024-04-01T00:00:00Z",
            updatedAt: "2024-04-10T00:00:00Z",
        },
        {
            id: "4",
            title: "Swift Package Manager",
            description: "Gestiona dependencias y modulariza tu código con Swift Package Manager.",
            content: "# Swift Package Manager\n\nSPM es la herramienta oficial...",
            category: "Swift",
            level: "Intermedio",
            date: "2023-11-05",
            imageUrl: "/images/tutorials/swiftui-intro.jpg",
            author: {
                name: "Alvaro Guerra",
                avatar: "/images/authors/alvaro.jpg",
                bio: "Desarrollador iOS con 5 años de experiencia especializado en SwiftUI y arquitecturas modernas de desarrollo móvil.",
            },
            tags: ["SPM", "Dependencias", "Modularización"],
            isPublished: true,
            slug: "swift-package-manager",
            readTime: 10,
            createdAt: "2024-04-01T00:00:00Z",
            updatedAt: "2024-04-10T00:00:00Z",
        },
        {
            id: "5",
            title: "Animaciones en SwiftUI",
            description: "Crea animaciones fluidas y atractivas en tus interfaces de SwiftUI.",
            content: "# Animaciones en SwiftUI\n\nLas animaciones son una parte esencial...",
            category: "SwiftUI",
            level: "Intermedio",
            date: "2023-11-20",
            imageUrl: "/images/tutorials/swiftui-intro.jpg",
            author: {
                name: "Alvaro Guerra",
                avatar: "/images/authors/alvaro.jpg",
                bio: "Desarrollador iOS con 5 años de experiencia especializado en SwiftUI y arquitecturas modernas de desarrollo móvil.",
            },
            tags: ["SwiftUI", "Animaciones", "UX"],
            isPublished: true,
            slug: "swiftui-animations",
            readTime: 9,
            createdAt: "2024-04-01T00:00:00Z",
            updatedAt: "2024-04-10T00:00:00Z",
        },
        {
            id: "6",
            title: "Introducción a Combine",
            description: "Aprende programación reactiva con el framework Combine de Apple.",
            content: "# Introducción a Combine\n\nCombine es un framework de programación reactiva...",
            category: "Frameworks",
            level: "Avanzado",
            date: "2023-12-01",
            imageUrl: "/images/tutorials/swiftui-intro.jpg",
            author: {
                name: "Alvaro Guerra",
                avatar: "/images/authors/alvaro.jpg",
                bio: "Desarrollador iOS con 5 años de experiencia especializado en SwiftUI y arquitecturas modernas de desarrollo móvil.",
            },
            tags: ["Combine", "Programación Reactiva", "Swift"],
            isPublished: true,
            slug: "combine-framework",
            readTime: 14,
            createdAt: "2024-04-01T00:00:00Z",
            updatedAt: "2024-04-10T00:00:00Z",
        },
        // Nuevos tutoriales
        {
            id: "7",
            title: "Gestión de Estado en SwiftUI",
            description: "Aprende a manejar el estado de tu aplicación con @State, @Binding, @ObservedObject y más.",
            content: "# Gestión de Estado en SwiftUI\n\nUno de los conceptos más importantes en SwiftUI...",
            category: "SwiftUI",
            level: "Intermedio",
            date: "2023-12-15",
            imageUrl: "/images/tutorials/swiftui-intro.jpg",
            author: {
                name: "Alvaro Guerra",
                avatar: "/images/authors/alvaro.jpg",
                bio: "Desarrollador iOS con 5 años de experiencia especializado en SwiftUI y arquitecturas modernas de desarrollo móvil.",
            },
            tags: ["SwiftUI", "State Management", "iOS"],
            isPublished: true,
            slug: "gestion-estado-swiftui",
            readTime: 11,
            createdAt: "2024-04-01T00:00:00Z",
            updatedAt: "2024-04-10T00:00:00Z",
        },
        {
            id: "8",
            title: "Protocolos en Swift",
            description: "Domina el uso de protocolos para crear código más flexible y reutilizable.",
            content: "# Protocolos en Swift\n\nLos protocolos son una parte fundamental...",
            category: "Swift",
            level: "Intermedio",
            date: "2024-01-05",
            imageUrl: "/images/tutorials/swiftui-intro.jpg",
            author: {
                name: "Alvaro Guerra",
                avatar: "/images/authors/alvaro.jpg",
                bio: "Desarrollador iOS con 5 años de experiencia especializado en SwiftUI y arquitecturas modernas de desarrollo móvil.",
            },
            tags: ["Swift", "Protocolos", "POP"],
            isPublished: true,
            slug: "protocolos-swift",
            readTime: 13,
            createdAt: "2024-04-01T00:00:00Z",
            updatedAt: "2024-04-10T00:00:00Z",
        },
        {
            id: "9",
            title: "Notificaciones Push en iOS",
            description: "Implementa notificaciones push en tus aplicaciones iOS paso a paso.",
            content: "# Notificaciones Push en iOS\n\nLas notificaciones push son esenciales...",
            category: "iOS",
            level: "Avanzado",
            date: "2024-01-18",
            imageUrl: "/images/tutorials/swiftui-intro.jpg",
            author: {
                name: "Alvaro Guerra",
                avatar: "/images/authors/alvaro.jpg",
                bio: "Desarrollador iOS con 5 años de experiencia especializado en SwiftUI y arquitecturas modernas de desarrollo móvil.",
            },
            tags: ["iOS", "Notificaciones", "APNS"],
            isPublished: true,
            slug: "notificaciones-push-ios",
            readTime: 16,
            createdAt: "2024-04-01T00:00:00Z",
            updatedAt: "2024-04-10T00:00:00Z",
        },
        {
            id: "10",
            title: "Introducción a Swift UI Testing",
            description: "Aprende a escribir pruebas automatizadas para tus interfaces de usuario en SwiftUI.",
            content: "# Introducción a Swift UI Testing\n\nLas pruebas automatizadas son cruciales...",
            category: "Testing",
            level: "Intermedio",
            date: "2024-02-01",
            imageUrl: "/images/tutorials/swiftui-intro.jpg",
            author: {
                name: "Alvaro Guerra",
                avatar: "/images/authors/alvaro.jpg",
                bio: "Desarrollador iOS con 5 años de experiencia especializado en SwiftUI y arquitecturas modernas de desarrollo móvil.",
            },
            tags: ["Testing", "XCTest", "UI Testing"],
            isPublished: true,
            slug: "swift-ui-testing",
            readTime: 14,
            createdAt: "2024-04-01T00:00:00Z",
            updatedAt: "2024-04-10T00:00:00Z",
        },
        {
            id: "11",
            title: "Arquitectura MVVM en SwiftUI",
            description: "Implementa el patrón Model-View-ViewModel en tus aplicaciones SwiftUI.",
            content: "# Arquitectura MVVM en SwiftUI\n\nEl patrón MVVM es ideal para SwiftUI...",
            category: "Arquitectura",
            level: "Intermedio",
            date: "2024-02-15",
            imageUrl: "/images/tutorials/swiftui-intro.jpg",
            author: {
                name: "Alvaro Guerra",
                avatar: "/images/authors/alvaro.jpg",
                bio: "Desarrollador iOS con 5 años de experiencia especializado en SwiftUI y arquitecturas modernas de desarrollo móvil.",
            },
            tags: ["SwiftUI", "MVVM", "Arquitectura"],
            isPublished: true,
            slug: "mvvm-swiftui",
            readTime: 12,
            createdAt: "2024-04-01T00:00:00Z",
            updatedAt: "2024-04-10T00:00:00Z",
        },
        {
            id: "12",
            title: "Localización en iOS",
            description: "Aprende a preparar tu aplicación para múltiples idiomas y regiones.",
            content:
                "# Localización en iOS\n\nLa localización permite que tu app llegue a usuarios de todo el mundo...",
            category: "iOS",
            level: "Principiante",
            date: "2024-03-01",
            imageUrl: "/images/tutorials/swiftui-intro.jpg",
            author: {
                name: "Alvaro Guerra",
                avatar: "/images/authors/alvaro.jpg",
                bio: "Desarrollador iOS con 5 años de experiencia especializado en SwiftUI y arquitecturas modernas de desarrollo móvil.",
            },
            tags: ["iOS", "Localización", "Internacionalización"],
            isPublished: true,
            slug: "localizacion-ios",
            readTime: 9,
            createdAt: "2024-04-01T00:00:00Z",
            updatedAt: "2024-04-10T00:00:00Z",
        },
        {
            id: "13",
            title: "Integración de MapKit en SwiftUI",
            description: "Aprende a integrar mapas interactivos en tus aplicaciones SwiftUI.",
            content: "# Integración de MapKit en SwiftUI\n\nLos mapas son una característica esencial...",
            category: "SwiftUI",
            level: "Intermedio",
            date: "2024-03-15",
            imageUrl: "/images/tutorials/swiftui-intro.jpg",
            author: {
                name: "Alvaro Guerra",
                avatar: "/images/authors/alvaro.jpg",
                bio: "Desarrollador iOS con 5 años de experiencia especializado en SwiftUI y arquitecturas modernas de desarrollo móvil.",
            },
            tags: ["SwiftUI", "MapKit", "Geolocalización"],
            isPublished: true,
            slug: "mapkit-swiftui",
            readTime: 11,
            createdAt: "2024-04-01T00:00:00Z",
            updatedAt: "2024-04-10T00:00:00Z",
        },
        {
            id: "14",
            title: "Desarrollo de Widgets para iOS",
            description: "Crea widgets interactivos para la pantalla de inicio con WidgetKit.",
            content: "# Desarrollo de Widgets para iOS\n\nLos widgets permiten a los usuarios...",
            category: "iOS",
            level: "Avanzado",
            date: "2024-04-01",
            imageUrl: "/images/tutorials/swiftui-intro.jpg",
            author: {
                name: "Alvaro Guerra",
                avatar: "/images/authors/alvaro.jpg",
                bio: "Desarrollador iOS con 5 años de experiencia especializado en SwiftUI y arquitecturas modernas de desarrollo móvil.",
            },
            tags: ["iOS", "WidgetKit", "SwiftUI"],
            isPublished: true,
            slug: "widgets-ios",
            readTime: 15,
            createdAt: "2024-04-01T00:00:00Z",
            updatedAt: "2024-04-10T00:00:00Z",
        },
        {
            id: "15",
            title: "Persistencia con UserDefaults",
            description: "Aprende a guardar y recuperar datos simples en iOS con UserDefaults.",
            content: "# Persistencia con UserDefaults\n\nUserDefaults es una forma sencilla...",
            category: "iOS",
            level: "Principiante",
            date: "2024-04-15",
            imageUrl: "/images/tutorials/swiftui-intro.jpg",
            author: {
                name: "Alvaro Guerra",
                avatar: "/images/authors/alvaro.jpg",
                bio: "Desarrollador iOS con 5 años de experiencia especializado en SwiftUI y arquitecturas modernas de desarrollo móvil.",
            },
            tags: ["iOS", "UserDefaults", "Persistencia"],
            isPublished: true,
            slug: "userdefaults-ios",
            readTime: 7,
            createdAt: "2024-04-01T00:00:00Z",
            updatedAt: "2024-04-10T00:00:00Z",
        },
        {
            id: "16",
            title: "Introducción a Swift Charts",
            description: "Crea visualizaciones de datos impresionantes con el framework Swift Charts.",
            content: "# Introducción a Swift Charts\n\nSwift Charts es un framework potente...",
            category: "SwiftUI",
            level: "Intermedio",
            date: "2024-05-01",
            imageUrl: "/images/tutorials/swiftui-intro.jpg",
            author: {
                name: "Alvaro Guerra",
                avatar: "/images/authors/alvaro.jpg",
                bio: "Desarrollador iOS con 5 años de experiencia especializado en SwiftUI y arquitecturas modernas de desarrollo móvil.",
            },
            tags: ["SwiftUI", "Swift Charts", "Visualización"],
            isPublished: true,
            slug: "swift-charts",
            readTime: 10,
            createdAt: "2024-04-01T00:00:00Z",
            updatedAt: "2024-04-10T00:00:00Z",
        },
        {
            id: "17",
            title: "Desarrollo de Extensiones para iOS",
            description: "Aprende a crear extensiones que amplíen la funcionalidad de tu app más allá de sus límites.",
            content: "# Desarrollo de Extensiones para iOS\n\nLas extensiones permiten que tu app...",
            category: "iOS",
            level: "Avanzado",
            date: "2024-05-15",
            imageUrl: "/images/tutorials/swiftui-intro.jpg",
            author: {
                name: "Alvaro Guerra",
                avatar: "/images/authors/alvaro.jpg",
                bio: "Desarrollador iOS con 5 años de experiencia especializado en SwiftUI y arquitecturas modernas de desarrollo móvil.",
            },
            tags: ["iOS", "Extensiones", "Share Extension"],
            isPublished: true,
            slug: "extensiones-ios",
            readTime: 13,
            createdAt: "2024-04-01T00:00:00Z",
            updatedAt: "2024-04-10T00:00:00Z",
        },
        {
            id: "18",
            title: "Animaciones Avanzadas en SwiftUI",
            description: "Domina técnicas avanzadas de animación para crear experiencias de usuario sorprendentes.",
            content: "# Animaciones Avanzadas en SwiftUI\n\nLas animaciones avanzadas pueden transformar...",
            category: "SwiftUI",
            level: "Avanzado",
            date: "2024-06-01",
            imageUrl: "/images/tutorials/swiftui-intro.jpg",
            author: {
                name: "Alvaro Guerra",
                avatar: "/images/authors/alvaro.jpg",
                bio: "Desarrollador iOS con 5 años de experiencia especializado en SwiftUI y arquitecturas modernas de desarrollo móvil.",
            },
            tags: ["SwiftUI", "Animaciones", "UX"],
            isPublished: true,
            slug: "animaciones-avanzadas-swiftui",
            readTime: 16,
            createdAt: "2024-04-01T00:00:00Z",
            updatedAt: "2024-04-10T00:00:00Z",
        },
        {
            id: "19",
            title: "Accesibilidad en iOS",
            description: "Aprende a hacer tus aplicaciones accesibles para todos los usuarios.",
            content: "# Accesibilidad en iOS\n\nLa accesibilidad es fundamental para crear apps inclusivas...",
            category: "iOS",
            level: "Intermedio",
            date: "2024-06-15",
            imageUrl: "/images/tutorials/swiftui-intro.jpg",
            author: {
                name: "Alvaro Guerra",
                avatar: "/images/authors/alvaro.jpg",
                bio: "Desarrollador iOS con 5 años de experiencia especializado en SwiftUI y arquitecturas modernas de desarrollo móvil.",
            },
            tags: ["iOS", "Accesibilidad", "VoiceOver"],
            isPublished: true,
            slug: "accesibilidad-ios",
            readTime: 11,
            createdAt: "2024-04-01T00:00:00Z",
            updatedAt: "2024-04-10T00:00:00Z",
        },
        {
            id: "20",
            title: "Desarrollo de Apps para macOS con SwiftUI",
            description: "Aprende a crear aplicaciones nativas para Mac utilizando SwiftUI.",
            content: "# Desarrollo de Apps para macOS con SwiftUI\n\nSwiftUI no solo es para iOS...",
            category: "macOS",
            level: "Intermedio",
            date: "2024-07-01",
            imageUrl: "/images/tutorials/swiftui-intro.jpg",
            author: {
                name: "Alvaro Guerra",
                avatar: "/images/authors/alvaro.jpg",
                bio: "Desarrollador iOS con 5 años de experiencia especializado en SwiftUI y arquitecturas modernas de desarrollo móvil.",
            },
            tags: ["macOS", "SwiftUI", "Catalyst"],
            isPublished: true,
            slug: "macos-swiftui",
            readTime: 14,
            createdAt: "2024-04-01T00:00:00Z",
            updatedAt: "2024-04-10T00:00:00Z",
        },
        {
            id: "21",
            title: "Introducción a Swift Macros",
            description: "Explora las nuevas macros de Swift para generar código en tiempo de compilación.",
            content: "# Introducción a Swift Macros\n\nLas macros son una característica poderosa...",
            category: "Swift",
            level: "Avanzado",
            date: "2024-07-15",
            imageUrl: "/images/tutorials/swiftui-intro.jpg",
            author: {
                name: "Alvaro Guerra",
                avatar: "/images/authors/alvaro.jpg",
                bio: "Desarrollador iOS con 5 años de experiencia especializado en SwiftUI y arquitecturas modernas de desarrollo móvil.",
            },
            tags: ["Swift", "Macros", "Metaprogramación"],
            isPublished: true,
            slug: "swift-macros",
            readTime: 17,
            createdAt: "2024-04-01T00:00:00Z",
            updatedAt: "2024-04-10T00:00:00Z",
        },
        {
            id: "22",
            title: "Desarrollo de Apps para Apple Vision Pro",
            description: "Aprende a crear experiencias inmersivas para Apple Vision Pro con visionOS.",
            content: "# Desarrollo de Apps para Apple Vision Pro\n\nvisionOS abre un nuevo mundo...",
            category: "visionOS",
            level: "Avanzado",
            date: "2024-08-01",
            imageUrl: "/images/tutorials/swiftui-intro.jpg",
            author: {
                name: "Alvaro Guerra",
                avatar: "/images/authors/alvaro.jpg",
                bio: "Desarrollador iOS con 5 años de experiencia especializado en SwiftUI y arquitecturas modernas de desarrollo móvil.",
            },
            tags: ["visionOS", "RealityKit", "SwiftUI"],
            isPublished: true,
            slug: "visionos-development",
            readTime: 18,
            createdAt: "2024-04-01T00:00:00Z",
            updatedAt: "2024-04-10T00:00:00Z",
        },
        {
            id: "23",
            title: "Desarrollo de Apps para Apple Watch",
            description: "Crea aplicaciones para watchOS utilizando SwiftUI y las APIs específicas del reloj.",
            content: "# Desarrollo de Apps para Apple Watch\n\nwatchOS ofrece oportunidades únicas...",
            category: "watchOS",
            level: "Intermedio",
            date: "2024-08-15",
            imageUrl: "/images/tutorials/swiftui-intro.jpg",
            author: {
                name: "Alvaro Guerra",
                avatar: "/images/authors/alvaro.jpg",
                bio: "Desarrollador iOS con 5 años de experiencia especializado en SwiftUI y arquitecturas modernas de desarrollo móvil.",
            },
            tags: ["watchOS", "SwiftUI", "Complicaciones"],
            isPublished: true,
            slug: "watchos-development",
            readTime: 12,
            createdAt: "2024-04-01T00:00:00Z",
            updatedAt: "2024-04-10T00:00:00Z",
        },
        {
            id: "24",
            title: "Integración de Firebase en iOS",
            description: "Aprende a integrar Firebase para añadir autenticación, base de datos y más a tu app.",
            content: "# Integración de Firebase en iOS\n\nFirebase ofrece una suite completa...",
            category: "Frameworks",
            level: "Intermedio",
            date: "2024-09-01",
            imageUrl: "/images/tutorials/swiftui-intro.jpg",
            author: {
                name: "Alvaro Guerra",
                avatar: "/images/authors/alvaro.jpg",
                bio: "Desarrollador iOS con 5 años de experiencia especializado en SwiftUI y arquitecturas modernas de desarrollo móvil.",
            },
            tags: ["Firebase", "iOS", "Backend"],
            isPublished: true,
            slug: "firebase-ios",
            readTime: 15,
            createdAt: "2024-04-01T00:00:00Z",
            updatedAt: "2024-04-10T00:00:00Z",
        },
    ];

    // Si limit es 0 o negativo, devolver todos los tutoriales
    if (limit <= 0) {
        return tutorials.filter((tutorial) => tutorial.isPublished);
    }

    // De lo contrario, devolver solo la cantidad solicitada
    return tutorials.filter((tutorial) => tutorial.isPublished).slice(0, limit);
}

export async function fetchTutorialBySlug(slug: string): Promise<Tutorial | null> {
    const tutorials = await fetchTutorials(0);
    return tutorials.find((tutorial) => tutorial.slug === slug) || null;
}

export async function fetchTutorialById(id: string): Promise<Tutorial | null> {
    const tutorials = await fetchTutorials(0);
    return tutorials.find((tutorial) => tutorial.id === id) || null;
}
